# Generated by Django 2.2.1 on 2019-06-04 11:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('marmeladenladen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ingredients',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
